language: node_js
node_js:
   - 0.4
   - 0.6
   - 0.7
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm install servedir"
notifications:
  email:
    - tyler@sleekcode.net
